[package]
name = "commons-identity-service"
description = "Reference Community Authority, Issuer, and Verifier service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
clap.workspace = true
commons-identity-core = { version = "0.1.0-preview.2", path = "../commons-identity-core" }
http.workspace = true
hkdf.workspace = true
multibase.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
time.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
x25519-dalek.workspace = true
zeroize.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true

[lib]
name = "commons_identity_service"
path = "src/lib.rs"

[[bin]]
name = "commons-identity-service"
path = "src/main.rs"
