import type {
  ConsentReceipt,
  Device,
  Persona,
  RuntimeInfo,
  WalletState,
} from "./types";

export const browserRuntime: RuntimeInfo = {
  mode: "browser-preview",
  protocol: "commons-identity/1",
  appVersion: "0.1.0-preview.2",
  seededData: true,
  secretPersistence: "none",
  coreConnected: false,
};

export const personas: Persona[] = [
  {
    id: "persona-research",
    name: "Research persona",
    community: "Example Research Community",
    localSubjectHint: "local · 8b5d…c214",
    credentialCount: 3,
    credentials: [
      {
        id: "cred-membership",
        type: "Membership",
        label: "Active community member",
        issuer: "Example Research Community",
        validUntil: "2 Nov 2026",
        status: "active",
        scopes: ["Enter community", "Use member services"],
        policy: "Membership policy · 27c4…a109",
      },
      {
        id: "cred-role",
        type: "Role",
        label: "Research contributor",
        issuer: "Example Research Community",
        validUntil: "31 Aug 2026",
        status: "active",
        scopes: ["Contribute research", "Review drafts"],
        policy: "Contributor policy · 46ab…211e",
      },
      {
        id: "cred-capability",
        type: "Capability",
        label: "Research archive access",
        issuer: "Example Research Community",
        validUntil: "9 Aug 2026",
        status: "active",
        scopes: ["Read archive documents"],
        policy: "Archive access policy · d911…e807",
      },
    ],
  },
  {
    id: "persona-neighbourhood",
    name: "Neighbourhood persona",
    community: "Harbour Neighbourhood Assembly",
    localSubjectHint: "local · 37aa…019f",
    credentialCount: 2,
    credentials: [
      {
        id: "cred-resident",
        type: "Membership",
        label: "Assembly member",
        issuer: "Harbour Neighbourhood Assembly",
        validUntil: "18 Oct 2026",
        status: "active",
        scopes: ["Attend local assemblies"],
        policy: "Assembly membership · b57a…41c0",
      },
      {
        id: "cred-training",
        type: "Qualification",
        label: "Community safety induction",
        issuer: "Harbour Neighbourhood Assembly",
        validUntil: "12 Jul 2027",
        status: "active",
        scopes: ["Safety induction completed"],
        policy: "Safety training · 830f…6a32",
      },
    ],
  },
  {
    id: "persona-studio",
    name: "Studio persona",
    community: "North Quay Making Studio",
    localSubjectHint: "local · ae91…445c",
    credentialCount: 1,
    credentials: [
      {
        id: "cred-studio",
        type: "Role",
        label: "Workshop steward",
        issuer: "North Quay Making Studio",
        validUntil: "1 Sep 2026",
        status: "active",
        scopes: ["Open workshop", "Record safety checks"],
        policy: "Steward policy · a021…b77d",
      },
    ],
  },
];

export const devices: Device[] = [
  {
    id: "device-mac",
    name: "Koichi’s Mac",
    kind: "MacBook Pro · Secure Enclave",
    location: "Sydney, AU",
    lastSeen: "Now",
    addedAt: "12 Jul 2026",
    keyHint: "Ed25519 · 6a1f…090c",
    credentials: 6,
    status: "current",
  },
  {
    id: "device-phone",
    name: "Pocket phone",
    kind: "iPhone · Secure Enclave",
    location: "Sydney, AU",
    lastSeen: "18 minutes ago",
    addedAt: "14 Jul 2026",
    keyHint: "Ed25519 · f227…84bb",
    credentials: 5,
    status: "trusted",
  },
  {
    id: "device-laptop",
    name: "Travel laptop",
    kind: "MacBook Air · Secure Enclave",
    location: "Melbourne, AU",
    lastSeen: "3 days ago",
    addedAt: "19 Jul 2026",
    keyHint: "Ed25519 · 9cd3…0f11",
    credentials: 3,
    status: "trusted",
  },
];

export const receipts: ConsentReceipt[] = [
  {
    id: "receipt-archive",
    verifier: "Example Research Archive",
    purpose: "Open a protected research document",
    claims: ["Active membership", "Archive read permission"],
    createdAt: "2 Aug 2026 · 10:00",
    retentionUntil: "2 Aug 2026 · 10:05",
    onwardSharing: false,
    linkability: "community",
    requestHash: "sha256 · 59c2…31a8",
  },
  {
    id: "receipt-assembly",
    verifier: "Harbour Assembly Room",
    purpose: "Enter the monthly neighbourhood meeting",
    claims: ["Assembly membership"],
    createdAt: "29 Jul 2026 · 18:24",
    retentionUntil: "29 Jul 2026 · 18:29",
    onwardSharing: false,
    linkability: "community",
    requestHash: "sha256 · 07fa…e202",
  },
  {
    id: "receipt-studio",
    verifier: "North Quay Workshop Door",
    purpose: "Unlock the supervised workshop",
    claims: ["Workshop steward role"],
    createdAt: "28 Jul 2026 · 08:11",
    retentionUntil: "28 Jul 2026 · 08:16",
    onwardSharing: false,
    linkability: "community",
    requestHash: "sha256 · c201…fd33",
  },
];

export function createSeedState(): WalletState {
  return {
    screen: "identity",
    runtime: browserRuntime,
    personas: structuredClone(personas),
    selectedPersonaId: personas[0]?.id ?? "",
    selectedCredentialId: personas[0]?.credentials[0]?.id ?? "",
    devices: structuredClone(devices),
    receipts: structuredClone(receipts),
    selectedReceiptId: receipts[0]?.id ?? "",
    onboardingStep: 0,
    vaultLabel: "My identity vault",
    dialog: null,
    toast: null,
  };
}
